import { PortfolioHolding } from "../types/portfolio";

export const TOTAL_PORTFOLIO_INVESTMENT = 1543060;

export const INITIAL_PORTFOLIO_HOLDINGS: PortfolioHolding[] = [
  {
    id: "hdfc-bank",
    stockName: "HDFC Bank",
    exchangeCode: "HDFCBANK",
    sector: "Financial",
    purchasePrice: 1490,
    quantity: 50,
    investment: 74500,
    portfolioPercentage: 4.828,
    yfSymbol: "HDFCBANK.NS",
    gfSymbol: "HDFCBANK:NSE",
    notes: null
  },
  {
    id: "bajaj-finance",
    stockName: "Bajaj Finance",
    exchangeCode: "BAJFINANCE",
    sector: "Financial",
    purchasePrice: 6466,
    quantity: 15,
    investment: 96990,
    portfolioPercentage: 6.286,
    yfSymbol: "BAJFINANCE.NS",
    gfSymbol: "BAJFINANCE:NSE",
    notes: "Exit"
  },
  {
    id: "icici-bank",
    stockName: "ICICI Bank",
    exchangeCode: "532174",
    sector: "Financial",
    purchasePrice: 780,
    quantity: 84,
    investment: 65520,
    portfolioPercentage: 4.246,
    yfSymbol: "ICICIBANK.NS",
    gfSymbol: "ICICIBANK:NSE",
    notes: null
  },
  {
    id: "bajaj-housing",
    stockName: "Bajaj Housing",
    exchangeCode: "544252",
    sector: "Financial",
    purchasePrice: 130,
    quantity: 504,
    investment: 65520,
    portfolioPercentage: 4.246,
    yfSymbol: "BAJAJHFL.NS",
    gfSymbol: "BAJAJHFL:NSE",
    notes: null
  },
  {
    id: "savani-financials",
    stockName: "Savani Financials",
    exchangeCode: "511577",
    sector: "Financial",
    purchasePrice: 24,
    quantity: 1080,
    investment: 25920,
    portfolioPercentage: 1.68,
    yfSymbol: "MANTRA.BO",
    gfSymbol: "511577:BOM",
    notes: null
  },
  {
    id: "affle-india",
    stockName: "Affle India",
    exchangeCode: "AFFLE",
    sector: "Tech",
    purchasePrice: 1151,
    quantity: 50,
    investment: 57550,
    portfolioPercentage: 3.73,
    yfSymbol: "AFFLE.NS",
    gfSymbol: "AFFLE:NSE",
    notes: null
  },
  {
    id: "lti-mindtree",
    stockName: "LTI Mindtree",
    exchangeCode: "LTIM",
    sector: "Tech",
    purchasePrice: 4775,
    quantity: 16,
    investment: 76400,
    portfolioPercentage: 4.951,
    yfSymbol: "LTM.NS",
    gfSymbol: "LTIM:NSE",
    notes: null
  },
  {
    id: "kpit-tech",
    stockName: "KPIT Tech",
    exchangeCode: "542651",
    sector: "Tech",
    purchasePrice: 672,
    quantity: 61,
    investment: 40992,
    portfolioPercentage: 2.657,
    yfSymbol: "KPITTECH.NS",
    gfSymbol: "KPITTECH:NSE",
    notes: "Must exit"
  },
  {
    id: "tata-tech",
    stockName: "Tata Tech",
    exchangeCode: "544028",
    sector: "Tech",
    purchasePrice: 1072,
    quantity: 63,
    investment: 67536,
    portfolioPercentage: 4.377,
    yfSymbol: "TATATECH.NS",
    gfSymbol: "TATATECH:NSE",
    notes: "Must exit"
  },
  {
    id: "bls-e-services",
    stockName: "BLS E-Services",
    exchangeCode: "544107",
    sector: "Tech",
    purchasePrice: 232,
    quantity: 191,
    investment: 44312,
    portfolioPercentage: 2.872,
    yfSymbol: "BLSE.NS",
    gfSymbol: "BLSE:NSE",
    notes: null
  },
  {
    id: "tanla",
    stockName: "Tanla",
    exchangeCode: "532790",
    sector: "Tech",
    purchasePrice: 1134,
    quantity: 45,
    investment: 51030,
    portfolioPercentage: 3.307,
    yfSymbol: "TANLA.NS",
    gfSymbol: "TANLA:NSE",
    notes: null
  },
  {
    id: "dmart",
    stockName: "Dmart",
    exchangeCode: "DMART",
    sector: "Consumer",
    purchasePrice: 3777,
    quantity: 27,
    investment: 101979,
    portfolioPercentage: 6.609,
    yfSymbol: "DMART.NS",
    gfSymbol: "DMART:NSE",
    notes: "Must Exit"
  },
  {
    id: "tata-consumer",
    stockName: "Tata Consumer",
    exchangeCode: "532540",
    sector: "Consumer",
    purchasePrice: 845,
    quantity: 90,
    investment: 76050,
    portfolioPercentage: 4.929,
    yfSymbol: "TATACONSUM.NS",
    gfSymbol: "TATACONSUM:NSE",
    notes: null
  },
  {
    id: "pidilite",
    stockName: "Pidilite",
    exchangeCode: "500331",
    sector: "Consumer",
    purchasePrice: 2376,
    quantity: 36,
    investment: 85536,
    portfolioPercentage: 5.543,
    yfSymbol: "PIDILITIND.NS",
    gfSymbol: "PIDILITIND:NSE",
    notes: "Must exit"
  },
  {
    id: "tata-power",
    stockName: "Tata Power",
    exchangeCode: "500400",
    sector: "Power",
    purchasePrice: 224,
    quantity: 225,
    investment: 50400,
    portfolioPercentage: 3.266,
    yfSymbol: "TATAPOWER.NS",
    gfSymbol: "TATAPOWER:NSE",
    notes: null
  },
  {
    id: "kpi-green",
    stockName: "KPI Green",
    exchangeCode: "542323",
    sector: "Power",
    purchasePrice: 875,
    quantity: 50,
    investment: 43750,
    portfolioPercentage: 2.835,
    yfSymbol: "KPIGREEN.NS",
    gfSymbol: "KPIGREEN:NSE",
    notes: "Must exit"
  },
  {
    id: "suzlon",
    stockName: "Suzlon",
    exchangeCode: "532667",
    sector: "Power",
    purchasePrice: 44,
    quantity: 450,
    investment: 19800,
    portfolioPercentage: 1.283,
    yfSymbol: "SUZLON.NS",
    gfSymbol: "SUZLON:NSE",
    notes: "Must exit"
  },
  {
    id: "gensol",
    stockName: "Gensol",
    exchangeCode: "542851",
    sector: "Power",
    purchasePrice: 998,
    quantity: 45,
    investment: 44910,
    portfolioPercentage: 2.91,
    yfSymbol: "GENSOL.NS",
    gfSymbol: "GENSOL:NSE",
    notes: "Must exit"
  },
  {
    id: "hariom-pipes",
    stockName: "Hariom Pipes",
    exchangeCode: "543517",
    sector: "Pipe",
    purchasePrice: 580,
    quantity: 60,
    investment: 34800,
    portfolioPercentage: 2.255,
    yfSymbol: "HARIOMPIPE.NS",
    gfSymbol: "HARIOMPIPE:NSE",
    notes: "Must exit"
  },
  {
    id: "astral",
    stockName: "Astral",
    exchangeCode: "ASTRAL",
    sector: "Pipe",
    purchasePrice: 1517,
    quantity: 56,
    investment: 84952,
    portfolioPercentage: 5.505,
    yfSymbol: "ASTRAL.NS",
    gfSymbol: "ASTRAL:NSE",
    notes: null
  },
  {
    id: "polycab",
    stockName: "Polycab",
    exchangeCode: "542652",
    sector: "Pipe",
    purchasePrice: 2818,
    quantity: 28,
    investment: 78904,
    portfolioPercentage: 5.113,
    yfSymbol: "POLYCAB.NS",
    gfSymbol: "POLYCAB:NSE",
    notes: null
  },
  {
    id: "clean-science",
    stockName: "Clean Science",
    exchangeCode: "543318",
    sector: "Others",
    purchasePrice: 1610,
    quantity: 32,
    investment: 51520,
    portfolioPercentage: 3.339,
    yfSymbol: "CLEAN.NS",
    gfSymbol: "CLEAN:NSE",
    notes: "Must exit"
  },
  {
    id: "deepak-nitrite",
    stockName: "Deepak Nitrite",
    exchangeCode: "506401",
    sector: "Others",
    purchasePrice: 2248,
    quantity: 27,
    investment: 60696,
    portfolioPercentage: 3.933,
    yfSymbol: "DEEPAKNTR.NS",
    gfSymbol: "DEEPAKNTR:NSE",
    notes: null
  },
  {
    id: "fine-organic",
    stockName: "Fine Organic",
    exchangeCode: "541557",
    sector: "Others",
    purchasePrice: 4284,
    quantity: 16,
    investment: 68544,
    portfolioPercentage: 4.442,
    yfSymbol: "FINEORG.NS",
    gfSymbol: "FINEORG:NSE",
    notes: null
  },
  {
    id: "gravita",
    stockName: "Gravita",
    exchangeCode: "533282",
    sector: "Others",
    purchasePrice: 2037,
    quantity: 8,
    investment: 16296,
    portfolioPercentage: 1.056,
    yfSymbol: "GRAVITA.NS",
    gfSymbol: "GRAVITA:NSE",
    notes: null
  },
  {
    id: "sbi-life",
    stockName: "SBI Life",
    exchangeCode: "540719",
    sector: "Others",
    purchasePrice: 1197,
    quantity: 49,
    investment: 58653,
    portfolioPercentage: 3.801,
    yfSymbol: "SBILIFE.NS",
    gfSymbol: "SBILIFE:NSE",
    notes: "Must exit"
  }
];

export function getHoldingById(id: string): PortfolioHolding | undefined {
  return INITIAL_PORTFOLIO_HOLDINGS.find(
    (h) => h.id === id || h.exchangeCode.toLowerCase() === id.toLowerCase() || h.yfSymbol.toLowerCase() === id.toLowerCase()
  );
}

export function getAllHoldings(): PortfolioHolding[] {
  return INITIAL_PORTFOLIO_HOLDINGS;
}
